CC = i686-w64-mingw32-gcc
CFLAGS = -Wall -std=c99

all: gpa.exe
gpa.exe: gpa.o data.o calculate.o print.o
	$(CC) -o gpa.exe gpa.o data.o calculate.o print.o
gpa.o: gpa.c data.h print.h
	$(CC) -c gpa.c data.h print.h
data.o: data.c data.h
	$(CC) -c data.c data.h
calculate.o: data.h calculate.h calculate.c
	$(CC) -c data.h calculate.h calculate.c
print.o: print.c print.h
	$(CC) -c print.c print.h

clean:
	rm -rf *.o
	rm -rf *.gch
